POST http://localhost:5097/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin123"
}
####
POST http://localhost:5097/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiRnVsbE5hbWUiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImV4cCI6MTc4NTUxMzgwNSwiaXNzIjoiQUlTYWxlc0Fzc2lzdGFudCIsImF1ZCI6IkFJU2FsZXNBc3Npc3RhbnQifQ.9Ng9zVUrObnslhERYKPOpuLb2kSTLGTA_28k2RQzluw
GET http://localhost:5097/profile
Authorization: Bearer {{token}}

###
GET http://localhost:5097/profile/admin
Authorization: Bearer {{token}}
###
POST  http://localhost:5097/auth/register
Content-Type: application/json

{
  "username":"john",
  "password":"john123",
  "fullName":"John Smith",
  "role":"User",
  "registrationKey":"wrong"
}